# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
$:.unshift File.join(File.dirname(__FILE__),'..','..','lib')

require 'attr_trackable'
require 'database_cleaner'

RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'

  config.before(:suite){ DatabaseCleaner.strategy = :truncation }
  config.before(:each) do
    DatabaseCleaner.start
  end
  config.after(:each) do
    DatabaseCleaner.clean
  end
end

ActiveRecord::Base.establish_connection({
  :database => ":memory:",
  :adapter => 'sqlite3',
  :timeout => 500
})

ActiveRecord::Schema.define do
  create_table :attr_trackable_attribute_changes, :force => true do |t|
    t.string  :obj_type
    t.integer :obj_id
    t.string  :attrib
    t.text    :value_was
    t.text    :value_is
    t.string  :change_id
    t.integer :editor_id
    t.string  :editor_type

    t.timestamps
  end
end
